# Uncomment the next line to define a global platform for your project


target 'detuf8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for detuf8
  pod 'Aspects'
  pod 'SVProgressHUD'
  pod 'POP+MCAnimate'
  pod 'ReactiveObjC'

end
